### PR TITLE
Fix typo on the configuration

### PR DESCRIPTION
**Pull request by wisn**
This will fix https://github.com/infinitered/ignite/issues/1200

### CODE REVIEW

**Comment by GantMan** [comment]
SNEAKY!!!!  This is why I want more Typescript in my life

**Comment by wisn** [comment]
@GantMan lol
Ugh, why the test failed...

**Comment by GantMan** [comment]
I kicked them off again... sometimes these tests just fail a lot.  I hate that, but CI isn't that stable.

**Comment by GantMan** [comment]
thanks Wisnu!

**Pull request merged**
