### PR TITLE
add android back button support

### PR DESCRIPTION
**Pull request by leonardo2204**
Add support to Android back button
If you are willing to accept, and if you'd like, I can drop some docs also!

### CODE REVIEW

**Comment by GantMan** [comment]
Woah, missed this in a sea of Open source emails.  Yes!  Def do docs.

There's a linting error I'm not understanding.  Can you get the lint 100% clean, too?

**Comment by leonardo2204** [comment]
@GantMan Haha no problem dude!
I was gonna ask you exactly that, I just merged with master, I'm not understanding this strange error.
I'll try running the lint locally to see what happens!

Thanks

**Comment by leonardo2204** [comment]
@GantMan Got it man!
Added some docs and fixed the lint errors, everything is smooth now :)

**Comment by GantMan** [comment]
Great work!

**Comment by GantMan** [comment]
We'll be doing an updated release soon

**Comment by leonardo2204** [comment]
Thank you man, and sorry for bothering haha ;)

**Comment by GantMan** [comment]
no bother :)

**Pull request merged**
