### PR TITLE
Fixes  FAIL  Tests/StoriesTest.js

### PR DESCRIPTION
**Pull request by Amurmurmur**
● Test suite failed to run

    /node_modules/@storybook/react-native/dist/preview/components/OnDeviceUI/menu_open.png:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){�PNG
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:303:17)
      at Object.<anonymous> (node_modules/@storybook/react-native/dist/preview/components/OnDeviceUI/index.js:51:21)
      at Object.<anonymous> (node_modules/@storybook/react-native/dist/preview/index.js:47:19)

### CODE REVIEW

**Comment by GantMan** [comment]
Heya!  I just created a new project and the test ran clean.

Are you sure this is an issue?   Maybe we can get another person to test.

**Comment by sidferreira** [comment]
@GantMan There's no error in my brand new project.

**Comment by GantMan** [comment]
Closing this PR

**Comment by Amurmurmur** [comment]
@GantMan Upgrade to react-native 0.50.4 and try to run tests, upgrade to latest packages.
Here is my `package.info`:
```
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "clean": "rm -rf $TMPDIR/react-* && watchman watch-del-all && npm cache clean --force",
    "clean:android": "cd android/ && ./gradlew clean && cd .. && react-native run-android",
    "newclear": "rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build && rm -rf node_modules/ && npm cache clean --force && npm i",
    "test:watch": "jest --watch",
    "updateSnapshot": "jest --updateSnapshot",
    "coverage": "jest --coverage && open coverage/lcov-report/index.html || xdg-open coverage/lcov-report/index.html",
    "android:build": "cd android && ./gradlew assembleRelease",
    "android:install": "cd android && ./gradlew assembleRelease && ./gradlew installRelease",
    "android:hockeyapp": "cd android && ./gradlew assembleRelease && puck -submit=auto app/build/outputs/apk/app-release.apk",
    "android:devices": "$ANDROID_HOME/platform-tools/adb devices",
    "android:logcat": "$ANDROID_HOME/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V",
    "android:shake": "$ANDROID_HOME/platform-tools/adb devices | grep '\\t' | awk '{print $1}' | sed 's/\\s//g' | xargs -I {} $ANDROID_HOME/platform-tools/adb -s {} shell input keyevent 82",
    "storybook": "storybook start -p 7007",
    "lint": "standard --verbose | snazzy",
    "lintdiff": "git diff --name-only --cached --relative | grep '\\.js$' | xargs standard | snazzy",
    "fixcode": "standard --fix",
    "git-hook": "npm run lint -s && npm run test -s"
  },
  "dependencies": {
    "apisauce": "^0.14.0",
    "format-json": "^1.0.3",
    "lodash": "^4.17.2",
    "prop-types": "^15.5.10",
    "querystringify": "1.0.0",
    "ramda": "^0.25.0",
    "react": "16.1.1",
    "react-native": "0.50.4",
    "react-native-config": "^0.10.0",
    "react-native-drawer": "^2.3.0",
    "react-navigation": "^1.0.0-beta.7",
    "react-redux": "^5.0.2",
    "redux": "^3.6.0",
    "redux-persist": "^4.1.0",
    "redux-saga": "^0.16.0",
    "reduxsauce": "0.7.0",
    "seamless-immutable": "^7.0.1"
  },
  "devDependencies": {
    "@storybook/addon-storyshots": "^3.2.3",
    "@storybook/react-native": "^3.2.3",
    "babel-eslint": "8.0.2",
    "babel-jest": "21.2.0",
    "babel-plugin-ignite-ignore-reactotron": "^0.3.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react-native": "4.0.0",
    "enzyme": "^2.6.0",
    "husky": "^0.14.3",
    "ignite-ir-boilerplate": "^2.2.2",
    "ignite-standard": "^1.0.0",
    "jest": "21.2.1",
    "mockery": "^2.0.0",
    "react-addons-test-utils": "~15.6.2",
    "react-dom": "16.1.1",
    "react-test-renderer": "16.1.1",
    "reactotron-react-native": "^1.12.0",
    "reactotron-redux": "^1.11.1",
    "reactotron-redux-saga": "^1.11.1",
    "snazzy": "^7.0.0",
    "standard": "10.0.3"
  },
  "jest": {
    "testMatch": [
      "**/Tests/**/*.js",
      "**/?(*.)(spec|test).js?(x)"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "Tests/Setup.js"
    ],
    "setupFiles": [
      "./Tests/Setup"
    ],
    "preset": "react-native"
  },
  "config": {},
  "standard": {
    "parser": "babel-eslint",
    "globals": [
      "describe",
      "test",
      "jest",
      "expect",
      "fetch",
      "navigator",
      "__DEV__",
      "XMLHttpRequest",
      "FormData",
      "React$Element"
    ]
  }
}

```
That is what you will get when you run `yarn test`
```
 FAIL  Tests/StoriesTest.js
  ● Test suite failed to run

    /AwesomeProject/node_modules/@storybook/react-native/dist/preview/components/OnDeviceUI/menu_open.png:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){�PNG
                                                                                             ^
    
    SyntaxError: Invalid or unexpected token
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (node_modules/@storybook/react-native/dist/preview/components/OnDeviceUI/index.js:61:21)
      at Object.<anonymous> (node_modules/@storybook/react-native/dist/preview/index.js:47:19)
```

**Comment by ruddell** [comment]
@GantMan This PR is needed for v0.50.4 to pass tests

**Pull request merged**
