### PR TITLE
FT - enable HMR for reducers/sagas/containers

### PR DESCRIPTION
**Pull request by l1br3**
For an unknown reason there is still an error at first HMR but the state is being updated.
Hard to understand what happens but as we can now update the store on the fly, I PR.

<3

### CODE REVIEW

**Comment by GantMan** [comment]
@skellock - does this look good to you? 

Looks good to me!

**Comment by skellock** [comment]
Looks great, but i haven't tested it.  Thank you SO much for doing this.

**Comment by jamonholmgren** [comment]
Ref https://github.com/infinitered/ignite/issues/1121

**Comment by l1br3** [comment]
@skellock 
This is solving absolutely nothing except getting rid of the error (partly).
The state app is not refreshed. 

I've investigated a lot into it (5hours now) and finally [posted a question on SO](https://stackoverflow.com/questions/46490306/react-native-redux-hmr-connect) because I can't find the solution. 

To be clear with this PR, the error shown at first disconnect the app from the state. 
The state can now be updated BUT the app is disconnected from the state. 
I've managed to get totally rid of the error but the state is still disconnected.

I've also made [a repo](https://github.com/l1br3/ReactNative-Redux-HMR-Broken) to reproduce the issue. 
I'm tired of this one.

**Comment by jamonholmgren** [comment]
Ref #146 

Thanks so much for sticking with this, @l1br3 . Your tenacity is legendary.

**Comment by l1br3** [comment]
@jamonholmgren This must be unmerged, destroyed, forget and so on... 
How do we do ? I create a new PR that remove this part of code ? 
Replaced by https://github.com/infinitered/ignite-ir-boilerplate/pull/146

**Pull request merged**
