### PR TITLE
Introduce Storybook into Ignite

### PR DESCRIPTION
**Pull request by rmevans9**
In this PR I introduce Storybook and Storyshots to the core of the boilerplate and setup two basic stories against some components that ship with the boilerplate. I am adding this as I believe Storybook and Storyshots to be fantastic tools when building out a set of components like many end users of this boilerplate will be doing. This is not meant to be complete but rather a glimpse into what this type of integration could look like. If it is liked I can finish out writing the component stories so all components ship with storybook stories.

# What was added
Two new dependencies for Storybook and Storyshots, a storybook script, a few stories for existing components in the boilerplate, a stories test to run storyshots and the support storybook folder to help run storybook

# What needs to be done
- Write more stories
- Possibly clean up the implementation into the boilerplate
- Docs around storybook and storyshots
- Make sure storyshots runs on precommit or prepush hooks to ensure snapshots did not change

# What does this look like?
This is what Storybook looks like:
screen shot 2017-08-03 at 7 37 56 pm

For storyshots I will note pollute you with a snapshot file so I will just say that it generates your typical Jest snapshot for each and every story defined.

# How do you test it?
Storybook: Instead of running `(npm/yarn) start` in the project directory you run `(npm/yarn) run storybook` then launch the app normally (via `react-native run-ios` and `react-native run-android`). ANDROID NOTE: You will need to run `adb reverse tcp:7007 tcp:7007` before launching the app to ensure port 7007 is tunneled back to your computer

Storyshots: `npm test` will run the snapshot tests setup for stories.

### CODE REVIEW

**Comment by rmevans9** [comment]
Actually it has come to my attention that the need for `adb reverse tcp:7007 tcp:7007` is gone in version 3.2.3 (installed here). So you should be able to skip that command and it still work 🎉

**Comment by jamonholmgren** [comment]
This is awesome @rmevans9. Awesome. 👍

**Comment by rmevans9** [comment]
I'll work on cleaning this up and writing stories for the rest of the components today and take a look at working on the docs. Any pointers where you guys might want this documented would be appreciated

**Comment by rmevans9** [comment]
The rest of the stories have been written. To fix an issue with the story selector in the browser (an alternative way to switch stories then just on device) I had to bump `react-dom` up to match the `react` version. I am unsure if this breaks anything else in the boilerplate but I didn't find anything specifically that broke in my testing.

**Comment by nonameolsson** [comment]
AWESOME!

**Comment by GantMan** [comment]
I can't wait to sink my teeth into this!  Very cool.  Will play with it soon.  🎈

**Comment by jamonholmgren** [comment]
@rmevans9 Nice work on this! Where do you think would be the best place to document the new capabilities?

**Comment by rmevans9** [comment]
@jamonholmgren I am planning to look at the docs here in the next few days. I was planning on looking at that earlier this week but then hadn't gotten a chance to yet.

**Comment by rmevans9** [comment]
Some really basic docs added with a link to the storybook website where users can read more about it. I think that this covers all the bases so I am removing the WIP tag - feel free to merge when ready unless there is anything further you guys want on this one.

/cc @skellock @jamonholmgren @GantMan

**Comment by GantMan** [comment]
@rmevans9 - if you can fix the rebase conflict, we'll merge!!!!

**Comment by rmevans9** [comment]
I will get this done tonight.

**Comment by rmevans9** [comment]
@GantMan `master`->`this branch` complete. Interestingly enough there were no merge conflicts so I guess git just worked it out on its own.

**Comment by GantMan** [comment]
image

:(

**Comment by rmevans9** [comment]
hmm let me try that again

**Comment by rmevans9** [comment]
I've opened another one in hopes that GitHub will let that one merge because locally I can merge master into the storybook branch all day with no issues.... so confused.

**Comment by GantMan** [comment]
with a fresh pull on master and all?  That is strange.

**Pull request closed without merging**
