### PR TITLE
Support react-navigation 1.0.0-beta.28+

### PR DESCRIPTION
**Pull request by Amurmurmur**

### CODE REVIEW

**Comment by GantMan** [comment]
re-building to see if tests pass

**Comment by Amurmurmur** [comment]
@GantMan It was an issue with linting, since its fixed could you please check it again :)

**Comment by Rah1x** [comment]
So how do I get this update in my running app? ive upgraded my app to latest react-native and opther dependencies.. now this issue is pending

**Comment by Rah1x** [comment]
Ok so for those who have already a running project here is how to solve it:

**1. Get the latest (unpblished!) version of boilerplate:**
a) delete the `\node_modules\ignite-ir-boilerplate` directory and its content

b) npm install "git+https://github.com/infinitered/ignite-ir-boilerplate.git"
also replace in package.json
"ignite-ir-boilerplate": "git+https://github.com/infinitered/ignite-ir-boilerplate.git",

**2. follow this to make changes to CreateStore.js and ReduxNavigation.js
https://github.com/infinitered/ignite-ir-boilerplate/commit/8e09ce2c097eb200c77daf0c6a4b625ffbef4fa5

**Pull request merged**
