### PR TITLE
 upgrade react-native to v0.50.4 and most other packages to latest

### LINKED ISSUE #129: Uselss lib needs to come out
https://github.com/infinitered/ignite-ir-boilerplate/blob/master/boilerplate/package.json.ejs#L32

We no longer use drawer this way with React Navigation in place now.

Remove lib

### LINKED ISSUE #150: Trying to use react-native 0.49.3 breaks
I'm trying to create a new app with the latest stable release of react-native (v 0.49). Whilst the installation / set-up goes through fine, it fails horribly when I run 'react-native run-ios'. I know it's probably not officially supported by ignite but it will be useful. It also makes use of React 16.0.0 which has a number of improvements I would love to use. There also seem to be some peer dependency issues. When I however create a 'base' project using react-native-cli I don't get any of those errors which suggests issues with some of the libs used in ignite.

Set-up:

`ignite new IgniteSampleApp --react-native-version 0.49.3`

In the React Packager terminal I get the following error:

`ERROR  ENOENT: no such file or directory, lstat '/opt/Development/react-native/examples/IgniteSampleApp/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTTouchEvent.o-70e60c84'`

Also doing a npm list, gives the following dependency warnings:

```
npm ERR! peer dep missing: react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x, required by enzyme@2.9.1
npm ERR! peer dep missing: react@>=15.2.1 || 16.0.0-alpha.6 || 16.0.0-alpha.12, required by reactotron-react-native@1.12.3
npm ERR! peer dep missing: react-dom@^15.4.2, required by react-addons-test-utils@15.4.2
npm ERR! peer dep missing: @storybook/react@^3.2.12, required by @storybook/addon-storyshots@3.2.12
npm ERR! extraneous: node-pre-gyp@0.6.38 /opt/Development/react-native/examples/IgniteSampleApp/node_modules/node-pre-gyp
npm ERR! peer dep missing: react@react@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-inspector@2.2.0
npm ERR! peer dep missing: react@^0.14.7 || ^15.0.0, required by @storybook/react-fuzzy@0.4.0
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-icons@2.2.7
npm ERR! peer dep missing: react@react@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-inspector@2.2.0
npm ERR! peer dep missing: react@^0.14.7 || ^15.0.0, required by react-komposer@2.0.0
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-modal@2.4.1
npm ERR! peer dep missing: react@^15.5.4, required by react-treebeard@2.0.3
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-icons@2.2.7
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0, required by react-modal@2.4.1
npm ERR! peer dep missing: react-dom@^15.5.4, required by react-treebeard@2.0.3
npm ERR! peer dep missing: react@^0.14.3 || ^15.0.0, required by react-komposer@1.13.1
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-simple-di@1.2.0
npm ERR! peer dep missing: react@^0.14.7 || ^15.0.0, required by react-stubber@1.0.0
npm ERR! peer dep missing: react@^15.3.0 || ^16.0.0, required by radium@0.19.5
npm ERR! peer dep missing: react@^15.3.0 || ^16.0.0, required by velocity-react@1.3.3
npm ERR! peer dep missing: react-dom@^15.3.0 || ^16.0.0, required by velocity-react@1.3.3
npm ERR! peer dep missing: react@^15.0.0 || ^16.0.0, required by react-transition-group@1.2.1
npm ERR! peer dep missing: react-dom@^15.0.0 || ^16.0.0, required by react-transition-group@1.2.1
```

If anyone has solved these issues I would love to know more :)

Thx

### LINKED ISSUE #159: Upgrade to latest packages
A lot of packages are out of date. 

- Upgrade to latest versions of all packages
- Make required changes to boilerplate so it works with the latest packages.

I will try to make a PR for this. But someone else is of course welcome to do it also :)

### PR DESCRIPTION
**Pull request by ruddell**
Finally back on a stable React 🎉 

Fix #159 Upgrades dependencies and react-native 
Fix #129 Removes react-native-drawer
Fix #150 Most peer dependencies installed, storybook-react causes issues though so I left it uninstalled
Related to #119 Upgrade to Enzyme v3 and fix breaking change

For tests to pass, this PR is required: #166

### CODE REVIEW

**Comment by dead23angel** [comment]
@jamonholmgren When do you expect to merge this branch into a master?

**Comment by jamonholmgren** [comment]
@dead23angel I'll let @GantMan take this one -- thanks!

**Comment by GantMan** [comment]
Awesome!  I'm packing for a trip, so not sure on doing an NPM release until I get back.

**Comment by GantMan** [comment]
Just tested everything.  Looks like master is good to go with the 2 PRs needed.  Thanks so much @ruddell - will package up a release!

**Pull request merged**
