### PR TITLE
Adds Rehydrated flag to startup redux

### PR DESCRIPTION
**Pull request by sidferreira**
I don't know if this is actually a best practice, but many times I'm wondering if the rehydrate already finished.
This is what I usually do. So, this is also a suggestion to the boilerplate

### CODE REVIEW

**Comment by sidferreira** [comment]
If this is accepted, I would suggest rename "STARTUP" to "APP" or something, to hold more generic "global" information. For example: check if already asked the user for push permission (android).
Things like that.

**Comment by GantMan** [comment]
Did you see that @ryanlntn is creating an optional plugin for ignited projects?
https://github.com/infinitered/ignite/pull/1171

Do you think it's best that you make your change over there?  Once this plugin is in place, rehydration will be optional.

**Comment by sidferreira** [comment]
@GantMan Well, I see your point... The idea was to have it set up right at the start of the project. But I think the plugin can't modify the redux part. So maybe we can just add some docs explaining how to do it instead? Or, if we replace the constant by the actual string (bad pattern, I know) we can keep it there and have no dependency to the  persist plugin

**Comment by GantMan** [comment]
The plugin should be able to modify the startup reducer right?    Let's get feedback from Ryan.

**Comment by ryanlntn** [comment]
@GantMan @sidferreira I don't see why not. Just need to add a couple more `patchInFile` calls to update StartupRedux.

**Comment by sidferreira** [comment]
@ryanlntn I'm a little short in time to read how to do that. Would you add this feature in the plugin?

@GantMan I think we can close this one already

**Comment by GantMan** [comment]
cool feature none-the-less!  Let's update here if we find any blockers.

**Pull request closed without merging**
