### PR TITLE
Avoiding problems with redux saga

### PR DESCRIPTION
**Pull request by HelloEdit**
This code can cause an undefined error (not evaluating 'regeneratorRuntime.mark')
```
export default function * root () {
  yield all([
    // ... snip ....
  ])
}
```

Watch the issue below for more info ;)

https://github.com/facebook/react-native/issues/14838

### CODE REVIEW

**Comment by GantMan** [comment]
@robinheinze - isn't this what you were just evaluating?

**Comment by HelloEdit** [comment]
Have you look at the link of the issue? (If yes, then I did not understand the question: p)

The problem is that exporting a generator function creates a bug in some cases.

**Comment by HelloEdit** [comment]
@robinheinze @GantMan Like this

**Comment by GantMan** [comment]
Thanks @HelloEdit 

If @robinheinze agrees we'll merge!  She was working on exactly this, I believe.

**Comment by robinheinze** [comment]
My issue actually ended up being slightly different, and was solved by updating redux-saga to 0.15.6

**Comment by HelloEdit** [comment]
Hello @robinheinze, maybe you have updated your code like this:
```
function * root () {
  yield all([
    // ... snip ....
  ])
}

export default root
```
In this case, the code works as before (strange problem not ?)

**Comment by robinheinze** [comment]
I went ahead and included the babel upgrade in my PR for RN 0.47.2 (https://github.com/infinitered/ignite-ir-boilerplate/pull/132)

**Comment by HelloEdit** [comment]
Ok, Thank you @robinheinze ! 👍

**Pull request closed without merging**
