### PR TITLE
Flatlist  and SectionList generators add

### PR DESCRIPTION
**Pull request by GantMan**
I'll be needing these for my presentation in Poland.  Can't be caught generating OLD LISTVIEWS!  So I went ahead and did the templating for `FlatList` and `SectionList` generators.

### In this PR:
I deprecate `ignite g listview nachos` in favor of `ignite g list nachos` - so that you can choose in the walkthrough if you want `FlatList` or `SectionList` or `ListView`.

I also noticed our integration tests for lists were passing fictitiously - so I fixed them.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
This looks really good @GantMan . Need to rebase tho.

**Comment by GantMan** [comment]
@jamonholmgren you can rebase it easy enough in the github merge :)

**Comment by skellock** [comment]
Can you hook us up with a rebase plz? There’s conflicts.

**Comment by GantMan** [comment]
rebase and merged

**Comment by skellock** [comment]
Thx dude!

**Pull request merged**
