### PR TITLE
Remove login screen and related code

### PR DESCRIPTION
**Pull request by derekgreenberg**
This removes the Login Screen and related redux/saga/navigation/test code. The login screen is not accessible from a freshly Ignited app, so it will not be missed if removed.

### CODE REVIEW

**Comment by GantMan** [comment]
honestly sad to see this go.  Without moving it to a different plugin.  We has someone complain that the examples being removed were upsetting :(

**Comment by derekgreenberg** [comment]
I discussed this with @skellock this morning. The login screen probably doesn't warrant a plugin.

To address people complaining about removing examples, we can create and share Ignited apps that provide useful examples that will help people create their apps. So, for example, the example app would include all of the login code that was removed from the boilerplate and demonstrate how to integrate login via a redux-aware AppNavigation.js file so when the user logs in, the navigator opens a simple screen with text that indicates the user logged in successfully - and provides a logout button. When the logout button is tapped, the navigator opens the login screen.

**Comment by derekgreenberg** [comment]
Anyway, looks like someone will create a login plugin anyway: https://github.com/infinitered/ignite-ir-boilerplate/issues/71

**Comment by skellock** [comment]
I say merge it. As it stands, it's dead code. Looking forward to the example!

**Comment by cwagner22** [comment]
I was going to start creating the login example plugin but I agree that it may be better to have an example app including everything. If that's the case then I can close my ticket #71

But is it really worth it to create a separate app just for a few more examples? It's probably a good idea to keep `ignite-ir-boilerplate` with at least the current examples so I don't know what a separate app will have more except a login screen.

**Comment by GantMan** [comment]
I would love a full example app, too.  Wouldn't be such a bad idea to get a common need like "login screen" as a plugin at some point.  I say go ahead and merge, but let's not let it be forgotten to get this code somewhere soon.

**Comment by derekgreenberg** [comment]
@GantMan I'm working on a demo app that shows how to integrate react-navigation with the existing login screen/redux/saga/test code that this PR would remove. I am not ready to merge this sucker until my plan is completed. My plan:

1. complete the details of the demo app, just to get it saved in the IR repo. I have a working demo right now, but it can be improved. I'll push my updates to the existing repo ASAP: `https://github.com/infinitered/ignite-example-login`.
2. create a plugin that adds all the necessary files for the existing login screen
3. update the demo app to use the new plugin
4. everything should work in the demo app at this point, SHARE this demo app via documentation in Ignite somewhere - TBD.

**Pull request merged**
