### PR TITLE
extends Component consistency

### PR DESCRIPTION
**Pull request by jbreuer95**
Is some files React.Component was used and in some others the decoupled way was used.
With this PR i changed everything to the decoupled way (my preference) but i can also do it the other way around?

PS. this will conflict with my proptypes PR so if you decide to merge that one i can update this.

### CODE REVIEW

**Comment by jbreuer95** [comment]
Ill update this one 1 sec

**Comment by jamonholmgren** [comment]
Looks good, @jbreuer95 , can you fix conflicts once again? :)

**Comment by jbreuer95** [comment]
@jamonholmgren No conflicts on my local machine and pushed everything?

**Comment by jbreuer95** [comment]
Looks like i have to learn how to rebase...

**Comment by jamonholmgren** [comment]
Closed in favor of #105. :)

**Pull request closed without merging**
