### PR TITLE
use self-install the same way

### PR DESCRIPTION
**Pull request by GantMan**

### CODE REVIEW

**Comment by skellock** [comment]
Thanks @GantMan

**Comment by jamonholmgren** [comment]
FYI this breaks `ignite new Foo -b ../my-boilerplate`. You have to use a full path to get it to work. :(

**Comment by GantMan** [comment]
@jamonholmgren - go ahead an file a ticket, and I'll get relative paths working again.  Should be 1 line.

**Comment by jamonholmgren** [comment]
This issue fixes #63 by the way (@gantman and his _No description provided_ prs! 😉 )

**Pull request merged**
