### PR TITLE
Improves the folder/relative path components, also adds docs

### PR DESCRIPTION
**Pull request by sidferreira**
Based on #148, refactor #167 and add docs.
Thanks for the better way of doing it @baldursson

### CODE REVIEW

**Comment by jamonholmgren** [comment]
Any ideas why this is failing, @sidferreira ?

```shell
> ignite-ir-boilerplate@2.2.2 test /home/runner/ignite-ir-boilerplate
> jest

 PASS  test/react-native-version.test.js
 PASS  test/interface.test.js
 FAIL  test/generators-integration.test.js (125.82s)
  ● generators › generates a folder component

    expect(received).toBe(expected)
    
    Expected value to be (using ===):
      "file"
    Received:
      false
    
    Difference:
    
      Comparing two different types of values. Expected string but received boolean.
      
      at test (test/generators-integration.test.js:45:74)
      at process._tickCallback (../../../tmp/5896bc9d8f0434e4d23cc19418d1c776/IntegrationTest/internal/process/next_tick.js:109:7)

Test Suites: 1 failed, 2 passed, 3 total
Tests:       1 failed, 19 passed, 20 total
Snapshots:   0 total
Time:        126.396s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by sidferreira** [comment]
I’ll check

**Comment by sidferreira** [comment]
```npm test

> ignite-ir-boilerplate@2.2.2 test /Users/sidferreira/Dev/ignite-ir-boilerplate-sid
> jest

 PASS  test/react-native-version.test.js
 PASS  test/interface.test.js
 PASS  test/generators-integration.test.js (393.774s)

Test Suites: 3 passed, 3 total
Tests:       20 passed, 20 total
Snapshots:   0 total
Time:        395.06s
Ran all test suites.```

Locally it went OK...

**Comment by sidferreira** [comment]
I'm wondering if there’s a node version related issue. I use 8.9 locally

**Comment by sidferreira** [comment]
@jamonholmgren Fixed! :D

**Pull request merged**
